name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - name: run .txt file
      run: python sample.py
      env:
        TOKEN_SECRET_NAME: ${{ secrets.token }}
